import React, { useState } from 'react';
import { useAuthStore } from '../store/authStore';
import api from '../services/api';
import toast from 'react-hot-toast';

const Quiz: React.FC = () => {
  const { user } = useAuthStore();
  const [subject, setSubject] = useState('Mathematics');
  const [questions, setQuestions] = useState<any[]>([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [userAnswers, setUserAnswers] = useState<string[]>([]);
  const [showResults, setShowResults] = useState(false);
  const [loading, setLoading] = useState(false);

  const startQuiz = async () => {
    setLoading(true);
    try {
      // Generate quiz questions using AI
      const quizData = await api.post('/quiz', {
        userId: user?.id,
        subject,
        title: `${subject} Quiz`,
        totalQuestions: 10,
        questions: [], // Will be generated by AI in backend
      });
      setQuestions(quizData.data.questions);
      setUserAnswers(new Array(10).fill(''));
      setCurrentQuestion(0);
    } catch (error) {
      toast.error('Failed to generate quiz');
    } finally {
      setLoading(false);
    }
  };

  const handleAnswer = (answer: string) => {
    const updatedAnswers = [...userAnswers];
    updatedAnswers[currentQuestion] = answer;
    setUserAnswers(updatedAnswers);
  };

  const handleNext = () => {
    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(currentQuestion + 1);
    }
  };

  const handleSubmit = async () => {
    setLoading(true);
    try {
      const response = await api.post(`/quiz/${questions[0]?._id}/submit`, {
        userAnswers,
      });
      toast.success(`Quiz completed! Score: ${response.data.percentage.toFixed(1)}%`);
      setShowResults(true);
    } catch (error) {
      toast.error('Failed to submit quiz');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">📝 Quiz</h1>

      {questions.length === 0 ? (
        <div className="bg-white rounded-lg shadow-lg p-8">
          <h2 className="text-2xl font-bold mb-4">Start a Quiz</h2>
          <select
            value={subject}
            onChange={(e) => setSubject(e.target.value)}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg mb-4 focus:outline-none focus:ring-2 focus:ring-indigo-600"
          >
            <option>Mathematics</option>
            <option>Physics</option>
            <option>Chemistry</option>
            <option>Biology</option>
          </select>
          <button
            onClick={startQuiz}
            disabled={loading}
            className="w-full bg-indigo-600 text-white py-3 rounded-lg hover:bg-indigo-700 disabled:opacity-50"
          >
            {loading ? 'Generating Quiz...' : 'Start Quiz'}
          </button>
        </div>
      ) : (
        <div className="bg-white rounded-lg shadow-lg p-8">
          <div className="mb-6">
            <p className="text-gray-600">Question {currentQuestion + 1} of {questions.length}</p>
            <div className="w-full bg-gray-200 rounded-full h-2 mt-2">
              <div
                className="bg-indigo-600 h-2 rounded-full"
                style={{ width: `${((currentQuestion + 1) / questions.length) * 100}%` }}
              />
            </div>
          </div>

          <h2 className="text-xl font-bold mb-6">{questions[currentQuestion]?.question}</h2>

          <div className="space-y-3 mb-6">
            {questions[currentQuestion]?.options.map((option: string, idx: number) => (
              <button
                key={idx}
                onClick={() => handleAnswer(option)}
                className={`w-full p-4 rounded-lg text-left font-semibold transition ${
                  userAnswers[currentQuestion] === option
                    ? 'bg-indigo-600 text-white'
                    : 'bg-gray-100 hover:bg-gray-200'
                }`}
              >
                {option}
              </button>
            ))}
          </div>

          <div className="flex gap-4">
            <button
              onClick={handleNext}
              disabled={currentQuestion === questions.length - 1}
              className="flex-1 bg-gray-600 text-white py-2 rounded-lg hover:bg-gray-700 disabled:opacity-50"
            >
              Next
            </button>
            {currentQuestion === questions.length - 1 && (
              <button
                onClick={handleSubmit}
                disabled={loading}
                className="flex-1 bg-green-600 text-white py-2 rounded-lg hover:bg-green-700 disabled:opacity-50"
              >
                {loading ? 'Submitting...' : 'Submit Quiz'}
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default Quiz;